### ISSUE TITLE
Installation en échec si une JVM 32 bits n'est pas installée

### ISSUE THREAD

**Issue by MatthieuG** [alexnedjari/SoundLooper#19]
Installation en échec si la JVM 1.6 n'est pas installée

**Comment by MatthieuG** [comment]
En complément : une install incluant la JVM pourrait être appréciable

**Comment by alexnedjari** [comment]
Après test, le problème ne vient pas du fait qu'il faut une JMV 1.6, comme le laisserai penser le message, mais qu'il faut une JVM 32 bits
Je travaille dessus pour voir quelle est la meilleure façon de résoudre le problème

**Comment by alexnedjari** [comment]
La correction fait en sorte que le logiciel fonctionne tant qu'il y a une JVM >= 1.6 sur le poste.
Dans le cas où il n'y a pas de JVM, l'utilisateur devra la télécharger

A voir dans un second temps pour une install incluant la JVM
