### ISSUE TITLE
Navigation favoris/marqueurs par un jtree

### ISSUE THREAD

**Issue by MatthieuG** [alexnedjari/SoundLooper#25]
Il pourrait être bien d'offrir une navigation par arborescence des favoris et des marqueurs, comme c'est le cas sur les navigateurs web.
La navigation serait beaucoup plus simple.

**Comment by alexnedjari** [comment]
La demande #5 existe déjà sur le sujet, en ce qui concerne les favoris.
Pour ce qui est des marqueurs, ça me semble moins utile (On n'a jamais 50 marqueurs dans une chanson, donc l'affichage en liste me semble suffisant). Je clôture donc cette demande.
